analytics:
  google: G-26YBDNY933

algoliaSearch:
  enable: true
  appId: WGLWUNVPAC
  apiKey: c934d5fef7d441aa41dc944123fcc4d1
  indexName: blog

footer:
  beian:
    enable: false
    icp: 黑ICP备2024017409号-1