analytics:
  baidu: c56505b9e2e433cd252eb2d0260865ec
#   google: G-26YBDNY933

algoliaSearch:
  enable: true
  appId: WGLWUNVPAC
  apiKey: c934d5fef7d441aa41dc944123fcc4d1
  indexName: blog

gitter:
  enable: false

footer:
  beian:
    enable: true
    icp: 黑ICP备2024018382号-1
    provinceAbbr: 黑
    gonganNum: 23018302000140