analytics:
  baidu: 64c0cf6f73c0091651a43d1fb153a401
#   google: G-26YBDNY933

algoliaSearch:
  enable: true
  appId: WGLWUNVPAC
  apiKey: c934d5fef7d441aa41dc944123fcc4d1
  indexName: blog

footer:
  beian:
    enable: true
    icp: 黑ICP备2024018382号
    provinceAbbr: 黑
    gonganNum: 0