version: "3.9"

x-traefik-label: &traefik-label
  traefik.enable: true
  traefik.http.routers.blog.service: blog
  traefik.http.services.blog.loadbalancer.server.port: 80

services:

  blog:
    image: ${param_registry_url}/library/blog:main
    pull_policy: always
    container_name: blog
    labels:
      <<: *traefik-label
    expose:
      - "80"
    restart: always