version: "3.9"

x-traefik-label: &traefik-label
  traefik.enable: true
  traefik.http.routers.blog.service: blog
  traefik.http.services.blog.loadbalancer.server.port: 80

services:
  app:
    image: ${param_registry_repo}/library/blog:${param_release_version}
    pull_policy: always
    container_name: blog
    labels:
      <<: *traefik-label
    expose:
      - "80"
    restart: always
    
networks:
  default:
    name: local
    external: true